import { useState } from "react";
import { useNavigate } from "react-router";
import { Activity, BrainCircuit, Target, ArrowRight } from "lucide-react";

const onboardingSteps = [
  {
    title: "Sync your vitals automatically",
    description: "VitaAI connects with Health Connect to seamlessly read your heart rate, sleep, and activity data in real-time.",
    icon: Activity,
    color: "text-rose-500",
    bg: "bg-rose-500/10",
  },
  {
    title: "AI-powered personalized insights",
    description: "Your daily readiness score and actionable insights are generated by our advanced health AI, analyzing your trends.",
    icon: BrainCircuit,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
  },
  {
    title: "Crush your wellness goals",
    description: "Follow adaptive training, log smart meals via photo, and track hydration with our beautiful minimal dashboard.",
    icon: Target,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
  }
];

export function Onboarding() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);

  const handleNext = () => {
    if (step < onboardingSteps.length - 1) {
      setStep((s) => s + 1);
    } else {
      navigate("/auth");
    }
  };

  const handleSkip = () => {
    navigate("/auth");
  };

  return (
    <div className="relative flex h-full w-full flex-col px-6 pt-20 pb-12 transition-all duration-300">
      <div className="flex justify-end">
        <button 
          onClick={handleSkip}
          className="text-[13px] font-medium tracking-tight text-slate-400 transition hover:text-slate-900"
        >
          Skip
        </button>
      </div>

      <div className="relative flex flex-1 flex-col items-center justify-center">
        <div
          key={step}
          className="flex flex-col items-center text-center animate-in fade-in zoom-in duration-500"
        >
          <div className={`mb-8 flex h-32 w-32 items-center justify-center rounded-[2.5rem] shadow-[0_20px_40px_rgba(0,0,0,0.04),inset_0_1px_0_rgba(255,255,255,1)] ring-1 ring-white/60 backdrop-blur-2xl ${onboardingSteps[step].bg}`}>
            {(() => {
              const Icon = onboardingSteps[step].icon;
              return <Icon className={`h-12 w-12 ${onboardingSteps[step].color}`} strokeWidth={1.5} />;
            })()}
          </div>
          <h2 className="mb-3 text-2xl font-semibold tracking-tight text-slate-900">
            {onboardingSteps[step].title}
          </h2>
          <p className="max-w-[280px] text-[15px] leading-relaxed text-slate-500">
            {onboardingSteps[step].description}
          </p>
        </div>
      </div>

      <div className="mt-auto flex flex-col items-center gap-8">
        <div className="flex gap-2">
          {onboardingSteps.map((_, i) => (
            <div
              key={i}
              className={`h-1.5 rounded-full transition-all duration-300 ${i === step ? "bg-slate-900 w-6" : "bg-slate-900/15 w-1.5"}`}
            />
          ))}
        </div>

        <button
          onClick={handleNext}
          className="group relative flex h-14 w-full items-center justify-center overflow-hidden rounded-[24px] bg-slate-900 text-[15px] font-medium tracking-tight text-white shadow-[0_14px_30px_rgba(15,23,42,0.2)] transition-transform hover:scale-[1.02] active:scale-95"
        >
          <span className="relative z-10 flex items-center gap-2">
            {step === onboardingSteps.length - 1 ? "Get Started" : "Continue"}
            <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
          </span>
          <div className="absolute inset-0 z-0 bg-gradient-to-r from-transparent via-white/10 to-transparent translate-x-[-100%] transition-transform duration-500 group-hover:translate-x-[100%]" />
        </button>
      </div>
    </div>
  );
}